// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj-APdSkvvjzLyJz5Yi38wIj524U5a5pI',
    appId: '1:815867526766:web:9aeb568c5110bfc2fc707f',
    messagingSenderId: '815867526766',
    projectId: 'shoply-c6f3e',
    authDomain: 'shoply-c6f3e.firebaseapp.com',
    storageBucket: 'shoply-c6f3e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkVucRD2ui2yglIQC1g3ncR7GIercVZGs',
    appId: '1:815867526766:android:019b26bb46651a4bfc707f',
    messagingSenderId: '815867526766',
    projectId: 'shoply-c6f3e',
    storageBucket: 'shoply-c6f3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcssjAE0T6sWIGXI8uGdf_fs_l2-5ARGE',
    appId: '1:815867526766:ios:3086033cddee1aa0fc707f',
    messagingSenderId: '815867526766',
    projectId: 'shoply-c6f3e',
    storageBucket: 'shoply-c6f3e.appspot.com',
    iosClientId: '815867526766-luc5njvu5kv0grebabhvmuq5l1vl3656.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoply',
  );
}
